/content/documents/blog/politiek:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'mix:versionable']
  jcr:uuid: 38565185-ad7e-46a9-92cd-886a59b2b30a
  hippo:name: Politiek
  hippostd:foldertype: [new-document, new-folder]
  /nz-election-results:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 1ff3cb93-502f-4e30-8b91-77a2e4e30c88
    hippo:name: NZ Election Results
    /nz-election-results[1]:
      jcr:primaryType: xinmods:content
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 379f26b2-5d34-45d2-8cfa-12329a9e97a6
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-10-18T21:57:55.707+13:00
      hippostdpubwf:lastModificationDate: 2017-10-18T21:57:55.707+13:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: d62dc63f-080a-4d02-9dc6-935fa36c4841
      hippotranslation:locale: document-type-locale
      xinmods:description: ''
      xinmods:pageTitle: ''
      xinmods:title: NZ First and Labour
      /xinmods:thumbnail:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /xinmods:Information:
        jcr:primaryType: xinmods:postdetails
        xinmods:address: ''
        xinmods:contactName: ''
        xinmods:email: ''
        xinmods:endDate: 2017-10-25T22:00:00+13:00
        xinmods:locationName: ''
        xinmods:startDate: 2017-10-18T22:00:00+13:00
        xinmods:time: ''
    /nz-election-results[2]:
      jcr:primaryType: xinmods:content
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: ea8405f0-1aef-4a42-9d09-9db06657bac9
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-10-18T21:57:55.707+13:00
      hippostdpubwf:lastModificationDate: 2017-10-18T22:00:15.850+13:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: d62dc63f-080a-4d02-9dc6-935fa36c4841
      hippotranslation:locale: document-type-locale
      xinmods:description: ''
      xinmods:pageTitle: ''
      xinmods:title: NZ First and Labour
      /xinmods:thumbnail:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /xinmods:Information:
        jcr:primaryType: xinmods:postdetails
        xinmods:address: ''
        xinmods:contactName: ''
        xinmods:email: ''
        xinmods:endDate: 2017-10-25T22:00:00+13:00
        xinmods:locationName: ''
        xinmods:startDate: 2017-10-18T22:00:00+13:00
        xinmods:time: ''
    /nz-election-results[3]:
      jcr:primaryType: xinmods:content
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 36d42dcd-18ee-4c92-ad73-4b4f5d4d1160
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-10-18T21:57:55.707+13:00
      hippostdpubwf:lastModificationDate: 2017-10-18T22:00:15.850+13:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2017-10-18T22:00:18.046+13:00
      hippotranslation:id: d62dc63f-080a-4d02-9dc6-935fa36c4841
      hippotranslation:locale: document-type-locale
      xinmods:description: ''
      xinmods:pageTitle: ''
      xinmods:title: NZ First and Labour
      /xinmods:thumbnail:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /xinmods:Information:
        jcr:primaryType: xinmods:postdetails
        xinmods:address: ''
        xinmods:contactName: ''
        xinmods:email: ''
        xinmods:endDate: 2017-10-25T22:00:00+13:00
        xinmods:locationName: ''
        xinmods:startDate: 2017-10-18T22:00:00+13:00
        xinmods:time: ''
