definitions:
  config:
    /hst:platform/hst:configurations/xinmods/hst:workspace/hst:containers:
      jcr:primaryType: hst:containercomponentfolder
      /base:
        jcr:primaryType: hst:containercomponentfolder
        /top:
          jcr:primaryType: hst:containercomponent
          hst:label: Top
          hst:xtype: hst.vbox
        /footer:
          jcr:primaryType: hst:containercomponent
          hst:label: Footer
          hst:xtype: hst.vbox
      /homepage:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: Home Page Main
          hst:xtype: hst.vbox
      /pagenotfound:
        jcr:primaryType: hst:containercomponentfolder
        /main:
          jcr:primaryType: hst:containercomponent
          hst:label: Page-Not-Found Main
          hst:xtype: hst.vbox
