definitions:
  config:
    /hippo:configuration/hippo:queries/hippo:templates/new-content-folder:
      jcr:primaryType: hippostd:templatequery
      jcr:mixinTypes: ['hipposys:implementation']
      hippostd:icon: addfolder_ico
      hippostd:modify: [./_name, $name]
      hipposys:classname: org.hippoecm.repository.impl.query.DirectPath
      jcr:language: xpath
      jcr:statement: /jcr:root/hippo:configuration/hippo:queries/hippo:templates/new-folder/hippostd:templates/node()
      /hippostd:templates:
        jcr:primaryType: hippostd:templates
        /hippostd:folder:
          jcr:primaryType: hippostd:folder
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 4603538a-f912-4f50-9a0d-2792691615a4
          hippostd:foldertype: [new-content, new-content-folder]
