definitions:
  config:
    /hippo:configuration/hippo:queries/hippo:templates/new-xinmods-genericimageset-folder:
      jcr:primaryType: hippostd:templatequery
      hippostd:modify: [./_name, $name]
      jcr:language: xpath
      jcr:statement: /jcr:root/hippo:configuration/hippo:queries/hippo:templates/new-xinmods-genericimageset-folder/hippostd:templates/node()
      /hippostd:templates:
        jcr:primaryType: hippostd:templates
        /image gallery:
          jcr:primaryType: hippogallery:stdImageGallery
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 96e1d7bb-62eb-495a-b328-470e67739c4e
          hippostd:foldertype: [new-xinmods-genericimageset-folder]
          hippostd:gallerytype: ['xinmods:genericimageset']
