definitions:
  config:
    /hippo:namespaces/xinmods/listComponent:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 215c4971-b83c-4178-8457-40b276a6c77e
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: cb4f0e9b-55ed-4cb5-a25a-e9b1dfc2c528
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: bba1b9f5-a920-4fa1-9ffd-e9a124eda47c
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /titleLink:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:titleLink
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /basePath:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:basePath
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
            hipposysedit:validators: [required]
          /tags:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:tags
            hipposysedit:primary: false
            hipposysedit:type: String
          /tagSearchType:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:tagSearchType
            hipposysedit:primary: false
            hipposysedit:type: StaticDropdown
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: xinmods:listComponent
          xinmods:title: ''
          xinmods:tags: ['']
          /xinmods:titleLink:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /xinmods:basePath:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /titleLink:
            jcr:primaryType: frontend:plugin
            caption: Title links to
            field: titleLink
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /basePath:
            jcr:primaryType: frontend:plugin
            caption: Base path
            field: basePath
            hint: The base path from which the list will be constructed
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['hippostd:folder']
          /tags:
            jcr:primaryType: frontend:plugin
            caption: Tags
            field: tags
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /tagSearchType:
            jcr:primaryType: frontend:plugin
            caption: Search Type
            field: tagSearchType
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              selectable.options: Any tag,All tags
