definitions:
  config:
    /hippo:namespaces/xinmods/menu:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 2bbfaf08-8976-4708-911b-b319c67e3f3d
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: afeda88f-3efd-4697-bff6-cd64537a0684
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 83e645ae-72f7-4aff-9ff9-51064c54c47d
          hipposysedit:node: true
          hipposysedit:supertype: ['xinmods:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /image:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:image
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /items:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:items
            hipposysedit:primary: false
            hipposysedit:type: xinmods:menuitem
          /maxPerColumn:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:maxPerColumn
            hipposysedit:primary: false
            hipposysedit:type: Long
          /nMaxColumns:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:nMaxColumns
            hipposysedit:primary: false
            hipposysedit:type: Long
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: xinmods:menu
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          xinmods:title: ''
          xinmods:nMaxColumns: 0
          xinmods:maxPerColumn: 0
          jcr:uuid: e15ebaae-2f10-476a-8aef-d3c1fdc0ad3f
          hippostdpubwf:lastModificationDate: 2017-07-29T14:21:09.601+12:00
          hippostdpubwf:creationDate: 2017-07-29T14:21:09.601+12:00
          /xinmods:image:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /xinmods:items:
            jcr:primaryType: xinmods:menuitem
            xinmods:externalUrl: ''
            xinmods:item: ''
            xinmods:openInNewWindow: false
            /xinmods:icon:
              jcr:primaryType: hippogallerypicker:imagelink
              hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
              hippo:facets: []
              hippo:modes: []
              hippo:values: []
            /xinmods:internalLink:
              jcr:primaryType: hippo:mirror
              hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /image:
            jcr:primaryType: frontend:plugin
            caption: Image
            field: image
            hint: Optional image to be shown at the menu item
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /items:
            jcr:primaryType: frontend:plugin
            caption: Menu Items
            field: items
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /maxPerColumn:
            jcr:primaryType: frontend:plugin
            caption: Items per column
            field: maxPerColumn
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /nMaxColumns:
            jcr:primaryType: frontend:plugin
            caption: Max columns
            field: nMaxColumns
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
