definitions:
  config:
    /hippo:namespaces/xinmods/siteconfig:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 54f2c15c-77b5-4a62-b7cd-47d2a388aa0b
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 12bc03b6-cc80-4862-92d3-25bde86a5557
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 765c4601-8c6f-4b12-bb13-2b0e236284b3
          hipposysedit:node: true
          hipposysedit:supertype: ['xinmods:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /siteName:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:siteName
            hipposysedit:primary: false
            hipposysedit:type: String
          /headerMenu:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:headerMenu
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /footerMenu:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:footerMenu
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /logo:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:logo
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /favicon:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:favicon
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /homepage:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:homepage
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: xinmods:siteconfig
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          xinmods:siteName: ''
          jcr:uuid: 79e272c5-cc38-45f6-a79b-0677646057db
          hippostdpubwf:lastModificationDate: 2017-07-29T14:22:06.093+12:00
          hippostdpubwf:creationDate: 2017-07-29T14:22:06.093+12:00
          /xinmods:headerMenu:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /xinmods:footerMenu:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
          /xinmods:logo:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /xinmods:favicon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /xinmods:homepage:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /siteName:
            jcr:primaryType: frontend:plugin
            caption: Site name
            field: siteName
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /headerMenu:
            jcr:primaryType: frontend:plugin
            caption: Header Menu
            field: headerMenu
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['xinmods:menu']
          /footerMenu:
            jcr:primaryType: frontend:plugin
            caption: Footer Menu
            field: footerMenu
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: ['xinmods:menu']
          /logo:
            jcr:primaryType: frontend:plugin
            caption: Logo
            field: logo
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /favicon:
            jcr:primaryType: frontend:plugin
            caption: Favicon
            field: favicon
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /homepage:
            jcr:primaryType: frontend:plugin
            caption: Homepage
            field: homepage
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
