definitions:
  config:
    /hippo:namespaces/xinmods/textComponent:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 70aa7837-fd76-4214-91f4-94881178deaf
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 045306d0-b2fd-4389-98bf-b9afcf76375b
        /hipposysedit:nodetype[1]:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: b0e3cd2b-621f-4191-9f97-f7476903baa1
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /html:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:html
            hipposysedit:primary: false
            hipposysedit:type: Html
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype[1]:
          jcr:primaryType: xinmods:textComponent
          xinmods:html: ''
          xinmods:textWrap: false
          /xinmods:image:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /html:
            jcr:primaryType: frontend:plugin
            caption: Html
            field: html
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
