definitions:
  config:
    /hippo:namespaces/xinmods/twoColumn:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 9e730a07-d9f1-4156-9471-768ade4c834d
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 73efe4a2-f47d-4dce-b452-1e189e390a67
        /hipposysedit:nodetype[1]:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 0c5af5cc-8794-4e74-84e5-bad6d4961992
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /Left column:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: xinmods:Left column
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
          /Right column:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: xinmods:Right column
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype[1]:
          jcr:primaryType: xinmods:twoColumn
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.variant: row
          /Left column:
            jcr:primaryType: frontend:plugin
            caption: Left column
            compoundList: xinmods:galleryComponent,xinmods:imageComponent,xinmods:textComponent,xinmods:textImageComponent
            contentPickerType: links
            field: Left column
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /Right column:
            jcr:primaryType: frontend:plugin
            caption: Right column
            compoundList: xinmods:galleryComponent,xinmods:imageComponent,xinmods:textComponent,xinmods:textImageComponent
            contentPickerType: links
            field: Right column
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
