definitions:
  config:
    /hippo:configuration/hippo:queries/hippo:templates/new-xinmods-genericimageset-image:
      jcr:primaryType: hippostd:templatequery
      hippostd:modify: [./_name, $name, ./_node/_name, $name]
      jcr:language: xpath
      jcr:statement: /jcr:root/hippo:configuration/hippo:queries/hippo:templates/new-xinmods-genericimageset-image/hippostd:templates/node()
      /hippostd:templates:
        jcr:primaryType: hippostd:templates
        /image:
          jcr:primaryType: hippo:handle
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: f0da6a1c-eb23-4169-9e0d-b28480607163
          /image:
            jcr:primaryType: hippogallery:imageset
            jcr:mixinTypes: ['mix:versionable']
            jcr:uuid: a98d6f4d-c4c0-4e29-89b5-fad08c9fa59a
            /hippogallery:thumbnail:
              jcr:primaryType: hippogallery:image
              jcr:data:
                type: binary
                resource: /configuration/queries/templates/new-xinmods-genericimageset-image/templates/image/image_thumbnail.jpg
              jcr:encoding: UTF-8
              jcr:lastModified: 2008-03-26T12:03:00+01:00
              jcr:mimeType: image/jpeg
