definitions:
  config:
    /hippo:namespaces/xinmods/menuitem:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: c408c8eb-037e-412b-bdd9-d71a93aafd21
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 3f38f506-4c88-4a47-8397-c67a2e0829f6
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 11c0b4f5-1b5c-4851-890c-253a06470bb8
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /item:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:item
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [non-empty, required]
          /icon:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:icon
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
            hipposysedit:validators: [optional]
          /internalLink:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:internalLink
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
          /externalUrl:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:externalUrl
            hipposysedit:primary: false
            hipposysedit:type: String
          /openInNewWindow:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:openInNewWindow
            hipposysedit:primary: false
            hipposysedit:type: Boolean
          /Children:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: xinmods:Children
            hipposysedit:type: hippo:compound
            hipposysedit:validators: [contentblocks-validator]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: xinmods:menuitem
          xinmods:item: ''
          xinmods:externalUrl: ''
          xinmods:openInNewWindow: false
          /xinmods:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /xinmods:internalLink:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /item:
            jcr:primaryType: frontend:plugin
            caption: Item
            field: item
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /icon:
            jcr:primaryType: frontend:plugin
            caption: Icon
            field: icon
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /internalLink:
            jcr:primaryType: frontend:plugin
            caption: Internal Link
            field: internalLink
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /externalUrl:
            jcr:primaryType: frontend:plugin
            caption: External URL
            field: externalUrl
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /openInNewWindow:
            jcr:primaryType: frontend:plugin
            caption: Open in new window?
            field: openInNewWindow
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /Children:
            jcr:primaryType: frontend:plugin
            caption: Children
            compoundList: xinmods:menuitem
            contentPickerType: links
            field: Children
            plugin.class: org.onehippo.forge.contentblocks.ContentBlocksFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
