definitions:
  config:
    /hippo:namespaces/xinmods/postdetails:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 485763b0-3aa9-4094-a6a5-82a81252baa9
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: ac5ca20c-b358-4787-9e04-735b44b96333
        /hipposysedit:nodetype[1]:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 7844656c-4f0e-4ddd-95cb-c14d64b4a728
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /startDate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:startDate
            hipposysedit:primary: false
            hipposysedit:type: Date
          /endDate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:endDate
            hipposysedit:primary: false
            hipposysedit:type: Date
          /time:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:time
            hipposysedit:primary: false
            hipposysedit:type: String
          /contactName:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:contactName
            hipposysedit:primary: false
            hipposysedit:type: String
          /locationName:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:locationName
            hipposysedit:primary: false
            hipposysedit:type: String
          /email:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:email
            hipposysedit:primary: false
            hipposysedit:type: String
          /address:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:address
            hipposysedit:primary: false
            hipposysedit:type: Text
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype[1]:
          jcr:primaryType: xinmods:postdetails
          xinmods:address: ''
          xinmods:contactName: ''
          xinmods:email: ''
          xinmods:endDate: 0001-01-02T00:00:00+12:00
          xinmods:locationName: ''
          xinmods:startDate: 0001-01-02T00:00:00+12:00
          xinmods:time: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /startDate:
            jcr:primaryType: frontend:plugin
            caption: Start date
            field: startDate
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /endDate:
            jcr:primaryType: frontend:plugin
            caption: End Date
            field: endDate
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /time:
            jcr:primaryType: frontend:plugin
            caption: Time
            field: time
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /contactName:
            jcr:primaryType: frontend:plugin
            caption: Contact Name
            field: contactName
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /email:
            jcr:primaryType: frontend:plugin
            caption: Contact Email
            field: email
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /locationName:
            jcr:primaryType: frontend:plugin
            caption: Location Name
            field: locationName
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /address:
            jcr:primaryType: frontend:plugin
            caption: Address
            field: address
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
