definitions:
  config:
    /hippo:namespaces/xinmods/textImageComponent:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: efb2fd11-33a8-4014-a056-ba01f7a41aec
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 0ff2da27-f5a0-4784-89e3-e8648c6d76ff
        /hipposysedit:nodetype[1]:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: c37f85c1-2ddc-41af-b4af-ac5d86165060
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /html:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:html
            hipposysedit:primary: false
            hipposysedit:type: Html
          /imageLocation:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:imageLocation
            hipposysedit:primary: false
            hipposysedit:type: StaticDropdown
          /image:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:image
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /textWrap:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: xinmods:textWrap
            hipposysedit:primary: false
            hipposysedit:type: Boolean
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype[1]:
          jcr:primaryType: xinmods:textImageComponent
          xinmods:html: ''
          xinmods:textWrap: false
          /xinmods:image:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /html:
            jcr:primaryType: frontend:plugin
            caption: Html
            field: html
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /image:
            jcr:primaryType: frontend:plugin
            caption: Image
            field: image
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /textWrap:
            jcr:primaryType: frontend:plugin
            caption: Text wraps image?
            field: textWrap
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /imageLocation:
            jcr:primaryType: frontend:plugin
            caption: Image location?
            field: imageLocation
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              selectable.options: Image to the Left,Image to the Right
