definitions:
  config:
    /hippo:namespaces/xinmods/genericimageset:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 3118b556-87aa-4d75-8098-801762f7ff5c
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 4aa5637c-86ef-47e4-b361-848adf03dba5
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:node: true
          hipposysedit:supertype: ['hippogallery:imageset', 'hippogallery:relaxed']
          hipposysedit:uri: http://www.onehippo.org/xinmods/nt/1.0
          /filename:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:filename
            hipposysedit:type: String
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:description
            hipposysedit:type: String
          /thumbnail:
            jcr:primaryType: hipposysedit:field
            hipposysedit:autocreated: true
            hipposysedit:mandatory: true
            hipposysedit:path: hippogallery:thumbnail
            hipposysedit:primary: true
            hipposysedit:type: hippogallery:image
          /original:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: hippogallery:original
            hipposysedit:type: hippogallery:image
          /mobile:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: xinmods:mobile
            hipposysedit:type: hippogallery:image
          /tablet:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: xinmods:tablet
            hipposysedit:type: hippogallery:image
          /desktop:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: xinmods:desktop
            hipposysedit:type: hippogallery:image
          /widescreen:
            jcr:primaryType: hipposysedit:field
            hipposysedit:path: xinmods:widescreen
            hipposysedit:type: hippogallery:image
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: xinmods:genericimageset
          jcr:mixinTypes: ['mix:versionable']
          jcr:uuid: 323c8a93-b94a-4b75-a76a-40c08ef53523
          /hippogallery:thumbnail:
            jcr:primaryType: hippogallery:image
            jcr:data:
              type: binary
              resource: /namespaces/xinmods/genericimageset/prototypes/prototype/thumbnail/thumbnail.gif
            jcr:lastModified: 1970-01-01T00:00:00Z
            jcr:mimeType: image/gif
          /hippogallery:original:
            jcr:primaryType: hippogallery:image
            hippogallery:height: 0
            hippogallery:width: 0
            jcr:data:
              type: binary
              resource: /namespaces/xinmods/genericimageset/prototypes/prototype/original/original.gif
            jcr:lastModified: 1970-01-01T00:00:00Z
            jcr:mimeType: image/gif
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [model.compareTo, wicket.model, engine]
          frontend:services: [wicket.id]
          mode: edit
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /filename:
            jcr:primaryType: frontend:plugin
            caption: file name
            field: filename
            plugin.class: org.hippoecm.frontend.plugins.gallery.editor.FileNameDisplayPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /thumbnail:
            jcr:primaryType: frontend:plugin
            caption: thumbnail
            field: thumbnail
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /original:
            jcr:primaryType: frontend:plugin
            caption: original
            field: original
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /mobile:
            jcr:primaryType: frontend:plugin
            caption: mobile
            field: mobile
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /tablet:
            jcr:primaryType: frontend:plugin
            caption: tablet
            field: tablet
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /desktop:
            jcr:primaryType: frontend:plugin
            caption: desktop
            field: desktop
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
          /widescreen:
            jcr:primaryType: frontend:plugin
            caption: widescreen
            field: widescreen
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
