definitions:
  config:
    /hippo:configuration/hippo:modules/autoexport:
      /hippo:moduleconfig:
        autoexport:enabled: true
        autoexport:modules:
          operation: override
          type: string
          value: ['repository-data/config:/']
