definitions:
  config:
    /hst:hst/hst:configurations/hst:default/hst:catalog/essentials-catalog:
      jcr:primaryType: hst:containeritempackage
      /menu:
        jcr:primaryType: hst:containeritemcomponent
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:iconpath: images/essentials/catalog-component-icons/menu.png
        hst:label: Menu
        hst:parameternames: [menu]
        hst:parametervalues: [main]
        hst:template: essentials-menu
        hst:xtype: hst.item
