/content/documents/xinmods/site:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'mix:versionable']
  jcr:uuid: 942578ca-a5f1-42ed-8416-25c4d0a16ef7
  hippo:name: Site
  hippostd:foldertype: [new-document, new-folder]
  /content:
    jcr:primaryType: hippostd:folder
    jcr:mixinTypes: ['hippo:named', 'mix:versionable']
    jcr:uuid: c160fe80-0557-499e-932a-84c6c919eaa4
    hippo:name: Content
    hippostd:foldertype: [new-content, new-content-folder]
