definitions:
  config:
    /hst:hst/hst:configurations/xinmods/hst:templates:
      jcr:primaryType: hst:templates
      /base-layout:
        jcr:primaryType: hst:template
        hst:renderpath: jsp/xinmods/base-layout.jsp
      /pagenotfound-main:
        jcr:primaryType: hst:template
        hst:renderpath: jsp/xinmods/pagenotfound-main.jsp
