/hst:hst/hst:hosts/dev-localhost/localhost/hst:root/api:
  jcr:primaryType: hst:mount
  hst:alias: api
  hst:ismapped: false
  hst:namedpipeline: RestApiPipeline
  hst:types: [rest]
  hst:responseheaders: ['Access-Control-Allow-Origin: *']
  hst:subjectbasedsession: true
